const pageContent = {
    ID: {
      searchnav: "cari menu berdasar nama...",
      monthlist: [{label:"Jan",value:"1"},
                  {label:"Feb",value:"2"},
                  {label:"Mar",value:"3"},
                  {label:"Apr",value:"4"},
                  {label:"Mei",value:"5"},
                  {label:"Jun",value:"6"},
                  {label:"Jul",value:"7"},
                  {label:"Agu",value:"8"},
                  {label:"Sep",value:"9"},
                  {label:"Okt",value:"10"},
                  {label:"Nov",value:"11"},
                  {label:"Des",value:"12"}],
      monthlistlong: [{label:"Januari",value:"1"},
                      {label:"Februari",value:"2"},
                      {label:"Maret",value:"3"},
                      {label:"April",value:"4"},
                      {label:"Mei",value:"5"},
                      {label:"Juni",value:"6"},
                      {label:"Juli",value:"7"},
                      {label:"Agustus",value:"8"},
                      {label:"September",value:"9"},
                      {label:"Oktober",value:"10"},
                      {label:"November",value:"11"},
                      {label:"Desember",value:"12"}],
      list: "Daftar",
      loadingMessage: "Mohon Tunggu Permintaan Anda Sedang Diproses",
      userLogin: "User",
      company: "Company",
      name: "Nama",
      address: "Alamat",
      datanotfound: "tidak ditemukan !\n",
      dataconfirm: "sudah di konfirmasi !",
      datanotconfirm: "belum di konfirmasi !",
      confirmsuccess: "berhasil di konfimasi !",
      confirmfailed: "gagal di konfimasi !",
      addsuccess: "penambahan data berhasil !",
      addfailed: "penambahan data gagal !",
      updatesuccess: "ubah data berhasil !",
      updatefailed: "ubah data gagal !",
      savesuccess: "berhasil di save !",
      savefailed: "gagal di save !",
      deletesuccess: "berhasil di hapus !",
      deletefailed: "gagal di hapus !",
      refresh: "refresh",
      select: "Pilih",
      add: "Tambah",
      edit: "Ubah",
      delete: "Hapus",
      save: "Simpan",
      cancel: "Batal",
      confirmBy: "Dikonfirmasi",
      confirmDate: "Tgl Konfirmasi",
      noempty: "tidak boleh kosong !",
      nosame: "tidak boleh sama !",
      history: "History",
      print: "Cetak",
      updateBy: "User Ubah",
      updateDate: "Tgl. Ubah",
      for: "untuk",
      connectionErr: "Koneksi Internet/Jaringan bermasalah, urutan solusi: \n" +
                     "1. cek koneksi internet di komputer anda \n" +
                     "2. coba kembali beberapa saat lagi \n" +
                     "3. coba refresh halaman \n" +
                     "4. hubungi DBA untuk pengecekan ! \n",
      MS:{
        structure: "Struktur",
        structuretype: "Jenis Struktur",
        structurecode: "Kode Struktur",
        structurename: "Nama Struktur",
        divisi: "Divisi",
        period: "Periode",
        dummy: "Dummy",
        dummyshadow: "Butuh Shadow",
        vaccant: "Vaccant",
        employee: "Karyawan",
        employeeshadow: "Karyawan Shadow",
        position: "Jabatan",
        positionAds: "Jabatan Iklan",
        dateentry: "Tanggal Masuk",
        directspv: "Atasan Langsung",
        workcity: "Kota Kerja",
        workcitynotfound: "Kota Kerja tidak ditemukan",
        branch: "Cabang",
        Error: {
          Add: "Gagal melakukan proses Tambah, coba lakukan langkah berikut :\n" +
               "1. Pastikan ( Jenis Struktur - Periode - Divisi ), sudah terpilih \n" +
               "2. Tekan kembali tombol Pilih \n" +
               "3. Tekan kembali tombol Tambah",
          AddPeriod: "Gagal melakukan proses Tambah, \n" +
                     "hanya dapat melakukan penambahan pada periode saat ini ! \n",
          Update: "Gagal Ubah data, \n" +
                  "Pilih data terlebih dahulu !",
          dateinputempty: "Tanggal masuk tidak boleh kosong !",
          dateinputmin: "Tanggal masuk harus lebih besar dari ",
          nostucture: "Mohon pilih struktur terlebih dahulu !",
        },
        Tooltip: {
          modalByText: "tekan Enter untuk menampilkan daftar data ( sesuai isi, bila kosong semua data tampil )",
          modal: "tekan Enter untuk menampilkan daftar data",
        },
        Data:{
          nip: "NIP",
          name: "Nama",
          position: "Jabatan",
          datein: "Tgl.Masuk",
          dateout: "Tgl.Kluar",
          branch: "Cabang",
          city: "Kota",
        },
        Print:{
          printuser:"User print",
          printdate:"Tanggal print",
          structureTitle: "Daftar Struktur",
          historyTitle: "Daftar History Struktur",
        }
      }
    },
    EN: {
      searchnav: "search menu by name...",
      monthlist: [{label:"Jan",value:"1"},
                  {label:"Feb",value:"2"},
                  {label:"Mar",value:"3"},
                  {label:"Apr",value:"4"},
                  {label:"May",value:"5"},
                  {label:"Jun",value:"6"},
                  {label:"Jul",value:"7"},
                  {label:"Aug",value:"8"},
                  {label:"Sep",value:"9"},
                  {label:"Oct",value:"10"},
                  {label:"Nov",value:"11"},
                  {label:"Dec",value:"12"}],
      monthlistlong: [{label:"January",value:"1"},
                      {label:"February",value:"2"},
                      {label:"March",value:"3"},
                      {label:"April",value:"4"},
                      {label:"May",value:"5"},
                      {label:"June",value:"6"},
                      {label:"July",value:"7"},
                      {label:"August",value:"8"},
                      {label:"September",value:"9"},
                      {label:"October",value:"10"},
                      {label:"November",value:"11"},
                      {label:"December",value:"12"}],
      list: "List",
      loadingMessage: "Please Wait Your Request is Being Processed",
      userLogin: "User",
      company: "Company",
      name: "Name",
      address: "Address",
      emptyOR: "Please select Order Number first !",
      emptyprocod: "Please select Product first !",
      datanotfound: "not found !\n",
      dataconfirm: "has been confirmed !",
      datanotconfirm: "UnConfirmed !",
      confirmsuccess: "confirm success !",
      confirmnotsuccess: "confirm failed !",
      addsuccess: "Add success !",
      addfailed: "Add failed !",
      updatesuccess: "Update success !",
      updatefailed: "Update failed !",
      savesuccess: "save success !",
      savefailed: "save failed !",
      deletesuccess: "delete success !",
      deletenotsuccess: "delete failed !",
      refresh: "refresh",
      select: "Select",
      add: "Add",
      edit: "Update",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      confirmBy: "Comfirm By",
      confirmDate: "Confirm Date",
      noempty: "cannot be empty !",
      nosame: "cannot be same !",
      history: "History",
      print: "Print",
      updateBy: "User Update",
      updateDate: "Update Date",
      for: "for",
      connectionErr: "Internet/Network connection Error, solution step: \n" +
                     "1. cek your internet connection \n" +
                     "2. try again in a few more momments \n" +
                     "3. try to refresh the page \n" +
                     "4. contact DBA for troubleshouting \n",
      MS:{
        structure: "Structure",
        structuretype: "Structure Type",
        structurecode: "Structure Code",
        structurename: "Structure Name",
        divisi: "Division",
        period: "Period",
        dummy: "Dummy",
        dummyshadow: "Need Shadow",
        vaccant: "Vaccant",
        employee: "Employee",
        employeeshadow: "Shadow Employee",
        position: "Position",
        positionAds: "Position (Ads)",
        dateentry: "Date of entry",
        directspv: "Direct Supervisor",
        workcity: "Work City",
        workcitynotfound: "Work City not found",
        branch: "Branch",
        Error: {
          Add: "Add proccess Fail, try to do this step :\n" +
               "1. Make sure ( Struktur Type - Periode - Divisi ), already selected \n" +
               "2. Press the Select button again \n" +
               "3. Press the Add button again",
          AddPeriod: "Add proccess Fail, \n" +
                     "only available for current period ! \n",
          Update: "Update data failed, \n" +
                  "Select the data first !",
          dateinputempty: "Entry Date cannot be empty !",
          dateinputmin: "Entry Date must be greater than ",
          nostucture: "Please choose structure first !",
        },
        Tooltip: {
          modalByText: "press Enter to show data list ( depend on text, empty text to show all data )",
          modal: "press Enter to show data list",
        },
        Data:{
          nip: "NIP",
          name: "Name",
          position: "Position",
          datein: "Date In",
          dateout: "Date Out",
          branch: "Branch",
          city: "City",
        },
        Print:{
          printuser:"User print",
          printdate:"Print date",
          structureTitle: "Stucture List",
          historyTitle: "History Structure List",
        }
      },
    },
  };
  export default pageContent;
  