const pageContent = {
    ID: {
      searchnav: "cari menu berdasar nama...",
      monthlist: [{label:"Jan",value:"1"},
                  {label:"Feb",value:"2"},
                  {label:"Mar",value:"3"},
                  {label:"Apr",value:"4"},
                  {label:"Mei",value:"5"},
                  {label:"Jun",value:"6"},
                  {label:"Jul",value:"7"},
                  {label:"Agu",value:"8"},
                  {label:"Sep",value:"9"},
                  {label:"Okt",value:"10"},
                  {label:"Nov",value:"11"},
                  {label:"Des",value:"12"}],
      monthlistlong: [{label:"Januari",value:"1"},
                      {label:"Februari",value:"2"},
                      {label:"Maret",value:"3"},
                      {label:"April",value:"4"},
                      {label:"Mei",value:"5"},
                      {label:"Juni",value:"6"},
                      {label:"Juli",value:"7"},
                      {label:"Agustus",value:"8"},
                      {label:"September",value:"9"},
                      {label:"Oktober",value:"10"},
                      {label:"November",value:"11"},
                      {label:"Desember",value:"12"}],
      loadingMessage: "Mohon Tunggu Permintaan Anda Sedang Diproses",
      userLogin: "User",
      company: "Company",
      datanotfound: "tidak ditemukan !\n" +
                    "Pastikan data yang anda pilih sudah benar !",
      dataconfirm: "sudah di konfirmasi !",
      datanotconfirm: "belum di konfirmasi !",
      confirmsuccess: "berhasil di konfimasi !",
      confirmnotsuccess: "gagal di konfimasi !",
      deletesuccess: "berhasil di hapus !",
      deletenotsuccess: "gagal di hapus !",
      refresh: "refresh",
      add: "Tambah",
      edit: "Ubah",
      delete: "Hapus",
      save: "Simpan",
      cancel: "Batal",
      confirmBy: "Dikonfirmasi",
      confirmDate: "Tgl Konfirmasi",
      history: "History",
      print: "Cetak",
      updateBy: "User Ubah",
      updateDate: "Tgl. Ubah",
      MS:{
        structuretype: "Jenis Struktur",
        structure: "Struktur",
        divisi: "Divisi",
        period: "Periode",
        dummy: "Dummy",
        dummyshadow: "Dummy Shadow",
        employee: "Karyawan",
        employeeshadow: "Karyawan Shadow",
        position: "Jabatan",
        positionAds: "Jabatan Iklan",
        dateentry: "Tanggal Masuk",
        directspv: "Atasan Langsung",
        workcity: "Kota Kerja",
        branch: "Cabang",
        Data:{
          nip: "NIP",
          name: "Nama",
          position: "Jabatan",
          datein: "Tgl.Masuk",
          dateout: "Tgl.Kluar",
          branch: "Cabang",
          city: "Kota",
        }
      }
    },
    EN: {
      searchnav: "search menu by name...",
      monthlist: [{label:"Jan",value:"1"},
                  {label:"Feb",value:"2"},
                  {label:"Mar",value:"3"},
                  {label:"Apr",value:"4"},
                  {label:"May",value:"5"},
                  {label:"Jun",value:"6"},
                  {label:"Jul",value:"7"},
                  {label:"Aug",value:"8"},
                  {label:"Sep",value:"9"},
                  {label:"Oct",value:"10"},
                  {label:"Nov",value:"11"},
                  {label:"Dec",value:"12"}],
      monthlistlong: [{label:"January",value:"1"},
                      {label:"February",value:"2"},
                      {label:"March",value:"3"},
                      {label:"April",value:"4"},
                      {label:"May",value:"5"},
                      {label:"June",value:"6"},
                      {label:"July",value:"7"},
                      {label:"August",value:"8"},
                      {label:"September",value:"9"},
                      {label:"October",value:"10"},
                      {label:"November",value:"11"},
                      {label:"December",value:"12"}],
      loadingMessage: "Please Wait Your Request is Being Processed",
      userLogin: "User",
      company: "Company",
      emptyOR: "Please select Order Number first !",
      emptyprocod: "Please select Product first !",
      datanotfound: "not found !\n" +
                    "Make sure the selected data is correct !",
      dataconfirm: "has been confirmed !",
      datanotconfirm: "UnConfirmed !",
      confirmsuccess: "confirm success !",
      confirmnotsuccess: "confirm failed !",
      deletesuccess: "delete success !",
      deletenotsuccess: "delete failed !",
      refresh: "refresh",
      add: "Add",
      edit: "Update",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      confirmBy: "Comfirm By",
      confirmDate: "Confirm Date",
      history: "History",
      print: "Print",
      updateBy: "User Update",
      updateDate: "Update Date",
      MS:{
        structuretype: "Structure Type",
        structure: "Structure",
        divisi: "Division",
        period: "Period",
        dummy: "Dummy",
        dummyshadow: "Dummy Shadow",
        employee: "Employee",
        employeeshadow: "Shadow Employee",
        position: "Position",
        positionAds: "Position (Ads)",
        dateentry: "Date of entry",
        directspv: "Direct Supervisor",
        workcity: "Work City",
        branch: "Branch",
        Data:{
          nip: "NIP",
          name: "Name",
          position: "Position",
          datein: "Date In",
          dateout: "Date Out",
          branch: "Branch",
          city: "City",
        }
      },
    },
  };
  export default pageContent;
  